config:
	configID [int]
	configMemberFee [float]
	configResetPassFee [float]
	configAllSiteMenu [int]		## 1 = use site menu, 2 = use default menu.
	configNewsCategoryID [int]	## stores category for news.
	configManagerSiteID [int]	## id for managers site.

user:
	userID [int]
	userIC [varchar]
	userPassword [varchar]
	userEmail [varchar]
	userLevel [varchar]			## 1 = members (M), 2 = site manager (SM), 3 = cluster lead (CL), 4 = operation manager (OM), 99 = root admin (R)
	userStatus [int]			## 0 = inactive, 1 = active
	userCreatedDate [datetime]
	userCreatedUser [int]
	userLastLogin [datetime]

account:
	accountID [int]
	accountType [int]			## 1 = user account, 2 = site account
	accountRefID [int]			## if type 1, user.userID, else site.siteID.
	accountBalance [int]		## constantly updated on every transaction, for easy querying record.
	accountCreatedDate [datetime]
	accountCreatedUser [int]
	accountUpdatedDate [datetime]
	accountUpdatedUser [int]

account_transaction:
	accountTransactionID [int]
	accountTransactionType [varchar]		## like, registration, cybercafe-topup.
	accountTransactionRefID [int]			## if later got referenced from somewhere can use this.
	accountTransactionDestination [int]		## accountID.
	accountTransactionSource [int]			## accountID
	accountTransactionValue [float]			## value of this transaction.
	accountTransactionRemark [text]
	accountTransactionStatus [int]			## 0 = pending , 1 = success, 2 = cancelled.
	accountTransactionCreatedDate [int]
	accountTransactionCreatedUser [int]

user_profile:
	userProfileID [int]
	userID [int]
	userProfileTitle [int]		## 1 = mr, 2 = mrs
	userProfileFullName [varchar] ## an alias for userProfileFirstname
	userProfileLastName [varchar]
	userProfilePhoneNo [varchar]
	userProfileGender [int]		## 1 = male, 2 = female
	userProfilePOB [varchar]
	userProfileMarital [int]	## 1 = single, 2 = married, 3 = widow
	userProfileDOB [date]
	userProfileMobileNo [varchar]
	userProfileMailingAddress [text]
	userProfileAvatarPhoto [varchar]

user_profile_additional: ## additional info for user.
	userProfileAdditionalID [int]
	userID [int]
	userProfileOccupation [varchar]		##
	userProfileFacebook [varchar]		##
	userProfileTwitter [varchar]		##
	userProfileWeb [varchar]			##
	userProfileEcommerce [varchar]		##
	userProfileIntroductional [text]	##
	userProfileEducation [varchar]

user_activity:
	userActivityID [int]
	userID [int]
	userActivityTypeCode [varchar(5)]			## 1XX = komen, 2XX = forum, 3XX = activity, 4XX = fail, 5XX = keahlian, 6XX = kemaskini
	userActivityParameter [varchar]
	userActivityRefID [int]						## 1 reference table.
	userActivityCreatedDate [datetime]

user_activity_type:
	userActivityTypeID [int]
	userActivityTypeCode [varchar(5)]
	userActivityTypeMessage [varchar(255)]		## format example
	userActivityTypeCategory [int]				## 1 = komen,  2 = forum, 3 = activity, 4 = fail, 5 = keahlian, 6 = kemaskini

activity:
	activityID [int]
	siteID [int]
	activityType [int]				## 1 = event, 2 = training
	activityName [varchar]
	activitySlug [varchar]
	activitySlugOriginal [varchar]
	activityAddressFlag [int]		## 0 = use field activityAddress, 1 = use site info address.
	activityAddress [text]
	activityDescription [text]
	activityParticipation [int]		## 1 = open for all p1m member, 2 = closed to member, 3 = open for all.
	activityStartDate [datetime]
	activityEndDate [datetime]
	activityDateTimeType [int]		## 1 = multiple selection, 2 = single date. (not really important.)
	activityApprovalStatus [int]			## 0 = unapproved, 1 = approved, 2 = disapproved.
	activityCreatedUser [int]
	activityCreatedDate [datetime]
	activityUpdatedUser [int]
	activityUpdatedDate [datetime]
	activityAllDateAttendance [int]	## all-date compulsory. 1 = ya, 2 = free to choose.

activity_budget:			## incomplete.
	activityBudgedID [int]
	activityID [int]

activity_date:
	activityDateID [int]
	activityID [int]
	activityDateValue [date]		## date of the activity.
	activityDateStartTime [time]
	activityDateEndTime [time]

activity_user: ## joining table.
	activityUserID [int]
	activityID [int]
	userID [int]
	activityUserCreatedDate [datetime]
	activityUserCreatedUser [int]

activity_user_date:
	activityUserDateID [int]
	activityUserID [int]
	activityUserDateValue [date]	## attend date. i think better use date as the foreignkey than activityDateID.
	activityUserDateAttendance [int]	## 0 = not-signed, 1 = attend, 2 = absence
	activityUserDateCreatedDate [datetime]
	activityUserDateCreatedUser [int]
	activityUserDateUpdatedDate [datetime]
	activityUserDateUpdatedUser [int]

activity_article:
	activityArticleID [int]
	activityArticleType [int]		## 1 = report, 2 = reference
	articleID [int]
	activityID [int]
	activityArticleCreatedDate [datetime]
	activityArticleCreatedUser [int]

activity_album:
	activityAlbumID [int]
	activityID [int]
	siteAlbumID [int]
	activityAlbumCreatedDate [datetime]
	activityAlbumCreatedUser [int]

activity_comment:
	activityCommentID [int]
	activityID [int]
	userID [int]
	activityCommentValue [varchar]
	activityCreatedDate [datetime]
	activityCreatedUser [int]

event:
	eventID [int]
	activityID [int]
	eventType [int]				## 1 = lawatan
	eventRefID [int]				## if eventType == 1
	eventCreatedUser [int]
	eventCreatedDate [datetime]

training:
	trainingID [int]
	activityID [int]
	trainingType [int]			## 0 is default
	trainingMaxPax [int]

state:
	stateID [int]
	stateName [varchar]
	stateCode [varchar(10)]

site:
	siteID [int]
	stateID [int]
	siteName [varchar]
	siteSlug [varchar]
	siteCreatedUser [int]
	siteCreatedDate [datetime]
	siteUpdatedUser [int]
	siteUpdatedDate [datetime]
	siteRefID [int]				## the site_id for old pi1m site.

site_info:
	siteInfoID [int]
	siteID [int]
	siteInfoLatitude [varchar]
	siteInfoLongitude [varchar]
	siteInfoPhone [varchar]
	siteInfoAddress [text]
	siteInfoDescription [text]
	siteInfoFax [varchar]
	siteInfoTwitterUrl [varchar]
	siteInfoFacebookUrl [varchar]
	siteInfoEmail [varchar]
	siteInfoImage [varchar]

site_member:
	siteMemberID [int]
	siteID [int]
	userID [int]
	siteMemberStatus [int]			## 0 = in-active, 1 = active.	// activation require payment.
	siteMemberOutsider [int]		## 1 = yes, 0 = no.
	siteMemberImported [int]		##  0 = no (new registration), 1 = yes.

site_slider:
	siteSliderID [int]
	siteID [int]
	siteSliderType [int]		## 1 = site specific, 2 = general (added by admin.)
	siteSliderName [varchar]
	siteSliderImage [varchar]
	siteSliderLink [varchar]	## link for which and which.
	siteSliderTarget [int]		## 1 = normal, 2 = new tab.
	siteSliderStatus [int]		## 0 = inactive, 1 = active
	siteSliderCreatedDate [datetime]
	siteSliderCreatedUser [int]

site_message:	## a message from public
	siteMessageID [int]
	messageID [int]
	siteID [int]
	siteMessageType [int]		## 1 = public, 2 = members.
	siteMessageCategory [int]	## 1 = aduan, 2 = pertanyaan, 3 = cadangan
	siteMessageReadStatus [int]
	siteMessageReadUser [int]
	siteMessageStatus [int]		## 1 = active, 2 = closed.
	siteMessageCreatedUser [int]		## if public (1), will use table contact. if members, will use table member.

contact:
	contactID [int]
	contactName [varchar]
	contactEmail [varchar]
	contactPhoneNo [varchar]

message:
	messageID [int]
	messageSubject [varchar]
	messageContent [text]
	messageCreatedDate [datetime]

menu:
	menuID [int]
	siteID [int]
	menuParentID [int]
	menuType [int]		## 1 = top
	componentNo [int]
	menuName [varchar]
	menuRefID [int]		## if componentID = 1 (page), refer to page id.
	menuRoute [varchar] ## if componentNo = 99, custom. else, empty.
	menuNo [int]		## to sort by listing.

component:	## static record, 6 currently.
	componentNo [int]				## 1 = page, 2 = main (/), 3 =  activity, 4 = members, 5 = contact us, 99 = custom.
	componentName [varchar]
	componentRoute [varchar]		## controller/action or route.
	componentStatus [int]			## 0 = inactive (wont show menu), 1 = activated.

page: 		## by default, will create about me page.
	pageID [int]
	siteID [int]
	pageApprovedStatus [int]	## 0 = unapproved, 1 = approve, 2 = unapproved.
	pagePhoto [varchar]			## store path to page photo.
	pageName [varchar]
	pageSlug [varchar]			## page slug
	pageText [text]
	pageTextExcerpt [text]		## a shortened version for pageText
	pageType [int]			## 1 = default, 2 = manual, 3 = general page
	pageDefaultType [int]	## if pageType is 0, this column is 0. 1 = about-us, 2 = about-pengurus, 3 = about-kampung.
	pageCreatedUser [int]
	pageCreatedDate [datetime]
	pageUpdatedUser [int]
	pageUpdatedDate [datetime]

page_photo:
	pagePhotoID [int]
	pageID [int]
	photoID [int]

page_reference:
	pageReferenceID [int]
	pageParentID [int]
	pageID [int]

page_default:
	pageDefaultID [int]
	pageDefaultType [varchar]	## 1 = about-us, 2 = about-pengurus, 3 = about-kampung.
	pageDefaultName [varchar]
	pageDefaultSlug [varchar]

## site editor can see article with articleStatus = 1 (saved).
article:
	articleID [int]
	siteID [int]
	articleStatus [int]		## 0 = unapproved, 1 = approved, 2 = disapproved, 3 = draft
	articleSlug [varchar]
	articleOriginalSlug [varchar]
	articleName [varchar]
	articleText [text]
	articlePublishedDate [datetime]		## will only published after this date.
	articleCreatedUser [int]
	articleCreatedDate [datetime]
	articleUpdatedUser [int]
	articleUpdatedDate [datetime]

article_photo:
	photoArticleID [int]
	photoID [int]
	articleID [int]
	articlePhotoCreatedDate [datetime]
	articlePhotoCreatedUser [int]

article_tag:
	articleTagID [int]
	articleID [int]	## article ID
	articleTagName [varchar]

article_category:
	articleCategoryID [int]
	articleID [int]
	categoryID [int]

category:
	categoryID [int]
	categoryName [varchar]
	categoryParentID [int]
	categoryCreatedDate [datetime]
	categoryCreatedUser [int]

article_listed:
	articleListedID [int]
	articleID [int]

announcement:
	announcementID [int]
	siteID [int]					## 0 = all sites, !0 = specific site
	announcementStatus [int]		## 0 = not appeared, 1 = appeared, 2 = unapproved.
	announcementText [text]
	announcementLink [text]
	announcementCreatedUser [int]
	announcementCreatedDate [datetime]
	announcementUpdatedUser [int]
	announcementUpdatedDate [datetime]
	announcementExpiredDate [datetime]

site_manager:
	siteManagerID [int]
	userID [int]
	siteID [int]
	siteManagerStatus [int]		## 1 = active, 0 = deactived.
	siteManagerCreatedDate [datetime]
	siteManagerCreatedUser [int]
	siteManagerUpdatedDate [datetime]
	siteManagerUpdatedUser [int]

cluster:
	clusterID [int]
	clusterName [varchar]
	clusterCreatedDate [datetime]
	clusterCreatedUser [int]

cluster_site: # many site to one cluster.
	clusterSiteID [int]
	siteID [int]
	clusterID [int]

cluster_lead:
	clusterLeadID [int]
	clusterID [int]
	userID [int]
	clusterLeadStatus [int] ## 1 = active, 0 = inactive.
	clusterLeadCreatedDate [datetime]
	clusterLeadCreatedUser [int]

album:
	albumID [int]
	albumName [varchar]
	albumCoverImageName [varchar] ## relative url for photo.
	albumDescription [text]
	albumCreatedDate [datetime]
	albumCreatedUser [int]

site_album:
	siteAlbumID [int]
	siteAlbumSlug [varchar]
	siteAlbumSlugOriginal [varchar]
	albumID [int]
	siteID [int]
	siteAlbumType [int] ## 1 = activity-album.
	siteAlbumStatus [int] ## 1 = active, 2 = deleted.

site_photo:
	sitePhotoID [int]
	photoID [int]
	siteID [int]
	siteAlbumID [int]
	sitePhotoStatus [int]	## 1 = active, 2 = deleted.

user_album:
	userAlbumID [int]
	albumID [int]
	userID [int]

user_photo:
	userPhotoID [int]
	photoID [int]
	userID [int]
	userAlbumID [int]

photo:
	photoID [int]
	photoName [varchar]			## photo full saved name, (path included)
	photoOriginalName [varchar]	## original photo name.
	photoDescription [text]
	photoCreatedDate [datetime]
	photoCreatedUser [int]

site_request: ## table to store update request or anything regarding site, have, status.
	siteRequestID [int]
	siteRequestType [varchar]					## 1 = new pages, 2 = page edit, 3 = site edit, 4 = new site announcement
	siteID [int]
	siteRequestRefID [int]					## reference-id
	siteRequestData [text]
	siteRequestStatus [int]					## 0 = unapproved, 1 = approved, 2 = disapproved
	siteRequestCorrectionFlag [int]			## 0 = stay this way, 1 = require correction.
	siteRequestRemark [text]
	siteRequestApprovalRead [int]
	siteRequestCreatedDate [datetime]
	siteRequestCreatedUser [int]
	siteRequestUpdatedDate [datetime]
	siteRequestUpdatedUser [int]

site_request_correction:
	siteRequestCorrectionID [int]
	siteRequestID [int]
	siteRequestCorrectionMessage [text]
	siteRequestCorrectionLastData [text]
	siteRequestCorrectionCreatedDate [datetime]
	siteRequestCorrectionCreatedUser [int]
	siteRequestCorrectionUpdatedDate [datetime]
	siteRequestCorrectionUpdatedUser [int]
	siteRequestCorrectionStatus [int]		## 1 = active, 2 = updated.

token:
	tokenID [int]
	tokenType [int]		## 1 = reset password.
	tokenName [varchar]
	tokenStatus [int]	## status 1 = active, 2 = expired.
	tokenCreatedDate [datetime]
	tokenUpdatedDate [datetime]

token_resetpass:
	tokenResetpassID [int]
	tokenID [int]
	userID [int]
	tokenResetpassStatus [int] ## 0 = in-active, 1 = active (after user has accessed the link), 2 = reset success. 

log_login:
	logLoginID [int]
	userID [int]
	logLoginCreatedDate [datetime]
	logLoginIP [varchar]

log_error:
	logErrorID [int]
	logErrorMessage [text]
	logErrorCreatedDate [datetime]
	logErrorCreatedUser [int]
	logErrorStatus [int]		## 0 = un-attended, 1 = attended.

temp_user:
	tempUserID [int]
	temp_userid [int]
	temp_username [varchar]
	temp_usernameOriginal [varchar]
	temp_password [varchar]
	temp_totallogin [int]
	temp_lastlogin [datetime]
	temp_userright [int]
	temp_user_status [int]
	temp_name [varchar]
	temp_ic_no [varchar]
	temp_contact_no [varchar]
	temp_Address [text]
	temp_datecreated [datetime]
	temp_DOB [date]
	temp_POB [varchar]
	temp_Tel [varchar]
	temp_CBC_Site [varchar]
	temp_email [varchar]
	temp_Occupation [varchar]
	temp_Education [varchar]
	temp_Title [varchar]
	temp_activationCode [varchar]
	temp_Gender [varchar]
	temp_mobile [varchar]
	temp_cbc_siteRight [varchar]

## module : forum.
thread:
	threadID [int]
	siteID [int]
	threadCategoryID [int]
	threadTitle [varchar]
	threadDescription [text]
	threadCreatedDate [datetime]
	threadCreatedUser [int]

thread_post:
	threadPostID [int]
	threadID [int]
	threadPostTitle [varchar]
	threadPostBody [text]
	threadPostCreatedUser [int]
	threadPostCreatedDate [datetime]

thread_category:
	threadCategoryID [int]
	threadCategoryLevel [int]		## 1 - first level, 2 = second level.
	threadCategoryTitle [varchar]
	threadCategoryDescription [text]
	threadCategoryCreatedUser [int]
	threadCategoryCreatedDate [datetime]

## module : video
video:
	videoID [int]
	videoAlbumID [int]
	videoType [int]			# 1 = youtube
	videoRefID [varchar]
	videoName [varchar]
	videoCreatedDate [datetime]
	videoCreatedUser [int]

## album for video
video_album:
	videoAlbumID [int]
	siteID [int]
	videoAlbumName [varchar]
	videoAlbumSlug [varchar]
	videoAlbumOriginalSlug [varchar]
	videoAlbumDescription [text]
	videoAlbumThumbnail [varchar]
	videoAlbumCreatedDate [datetime]
	videoAlbumCreatedUser [int]

## module : file sharing.
file:
	fileID [int]
	filePath [varchar]
	fileFolderID [int]
	filePrivacy [int]		## 1 = private, 2 = public
	fileName [varchar]
	fileSlug [varchar]
	fileOriginalSlug [varchar]
	fileType [varchar]
	fileSize [int]
	fileDescription [text]
	fileCreatedDate [datetime]
	fileCreatedUser [int]

file_folder:
	fileFolderID [int]
	siteID [int]
	fileFolderPrivacy [int]	## 1 = private, 2 = public
	fileFolderName [varchar]
	fileFolderCreatedDate [datetime]
	fileFolderCreatedUser [int]

comment:
	commentID [int]
	commentType [int]
	commentRefID [int]
	userID [int]
	commentBody [text]
	commentCreatedDate [datetime]