user:
	userID [int]
	userIC [varchar]
	userPassword [varchar]
	userEmail [varchar]
	userLevel [varchar]			## 1 = members (M), 2 = site manager (SM), 3 = cluster lead (CL), 4 = operation manager (OM), 99 = root admin (R)
	userStatus [int]			## 0 = inactive, 1 = active
	userPremiumStatus [int]		## 0 = normal, 1 = premium user.
	userCreatedDate [datetime]
	userCreatedUser [int]

user_premium:
	userPremiumID [int]
	userID [int]
	userPremiumPayment [float]		## default 5
	userPremiumCreatedDate [datetime]
	userPremiumCreatedUser [int]

user_profile:
	userProfileID [int]
	userID [int]
	userProfileTitle [int]		## 1 = mr, 2 = mrs
	userProfileFullName [varchar]
	userProfilePhoneNo [varchar]
	userProfileGender [int]		## 1 = male, 2 = female
	userProfilePOB [varchar]
	userProfileMarital [int]	## 1 = single, 2 = married, 3 = widow
	userProfileDOB [date]
	userProfileMobileNo [varchar]
	userProfileMailingAddress [text]

user_activity:
	userActivityID [int]
	userID [int]
	userActivityTypeCode [varchar(5)]			## 1XX = komen, 2XX = forum, 3XX = activity, 4XX = fail, 5XX = keahlian, 6XX = kemaskini
	userActivityParameter [varchar]
	userActivityRefID [int]						## 1 reference table.
	userActivityCreatedDate [datetime]

user_activity_type:
	userActivityTypeID [int]
	userActivityTypeCode [varchar(5)]
	userActivityTypeMessage [varchar(255)]		## format example
	userActivityTypeCategory [int]				## 1 = komen,  2 = forum, 3 = activity, 4 = fail, 5 = keahlian, 6 = kemaskini

activity:
	activityID [int]
	siteID [int]
	activityType [int]				## 1 = event, 2 = training
	activityName [varchar]
	activitySlug [varchar]
	activitySlugOriginal [varchar]
	activityAddressFlag [int]		## 0 = use field activityAddress, 1 = use site info address.
	activityAddress [text]
	activityDescription [text]
	activityParticipation [int]		## 1 = open for all, 2 = closed to member
	activityStartDate [date]
	activityEndDate [date]
	activityApprovalStatus [int]			## 0 = unapproved, 1 = approved, 2 = disapproved.
	activityCreatedUser [int]
	activityCreatedDate [datetime]
	activityUpdatedUser [int]
	activityUpdatedDate [datetime]

activity_budget:			## incomplete.
	activityBudgedID [int]
	activityID [int]

activity_date:
	activityDateID [int]
	activityID [int]
	activityDateValue [date]

activity_time:
	activityTimeID [int]
	activityDateID [int]
	activityTimeStart [time]
	activityTimeEnd [time]

activity_user:
	activityUserID [int]
	userID [int]
	activityUserValue [int]			## 1 = join, 2 = no.
	activityUserCreatedDate [datetime]

activity_article:
	activityArticleID [int]
	articleID [int]
	activityID [int]

activity_album:
	activityAlbumID [int]
	activityID [int]
	albumID [int]
	activityAlbumCreatedDate [datetime]
	activityAlbumCreatedUser [int]

activity_comment:
	activityCommentID [int]
	activityID [int]
	userID [int]
	activityCommentValue [varchar]
	activityCreatedDate [datetime]
	activityCreatedUser [int]

event:
	eventID [int]
	activityID [int]
	eventName [varchar]
	eventType [int]				## 1 = lawatan
	eventRefID [int]				## if eventType == 1
	eventCreatedUser [int]
	eventCreatedDate [datetime]

training:
	trainingID [int]
	activityID [int]
	trainingName [varchar]
	trainingType [int]			## 0 is default
	trainingMaxPax [int]

state:
	stateID [int]
	stateName [varchar]
	stateCode [varchar(10)]

site:
	siteID [int]
	stateID [int]
	siteName [varchar]
	siteSlug [varchar]
	siteCreatedUser [int]
	siteCreatedDate [datetime]
	siteUpdatedUser [int]
	siteUpdatedDate [datetime]

site_info:
	siteInfoID [int]
	siteID [int]
	siteInfoLatitude [varchar]
	siteInfoLongitude [varchar]
	siteInfoPhone [varchar]
	siteInfoAddress [text]
	siteInfoDescription [text]
	siteInfoFax [varchar]
	siteInfoTwitterUrl [varchar]
	siteInfoFacebookUrl [varchar]
	siteInfoEmail [varchar]
	siteInfoImage [varchar]

site_member:
	siteMemberID [int]
	siteID [int]
	userID [int]
	siteMemberPremiumStatus [int]	## 0 = inactive, 1 = premium status

site_slider:
	siteSliderID [int]
	siteID [int]
	siteSliderType [int]		## 1 = site specific, 2 = general (added by admin.)
	siteSliderName [varchar]
	siteSliderImage [varchar]
	siteSliderLink [varchar]	## link for which and which.
	siteSliderTarget [int]		## 1 = normal, 2 = new tab.
	siteSliderStatus [int]		## 0 = inactive, 1 = active
	siteSliderCreatedDate [datetime]
	siteSliderCreatedUser [int]

site_message:	## a message from public
	siteMessageID [int]
	messageID [int]
	siteID [int]
	siteMessageType [int]		## 1 = public, 2 = members.
	siteMessageCategory [int]	## 1 = aduan, 2 = pertanyaan, 3 = cadangan
	siteMessageReadStatus [int]
	siteMessageReadUser [int]
	siteMessageStatus [int]		## 1 = active, 2 = closed.
	siteMessageCreatedUser [int]		## if public (1), will use table contact. if members, will use table member.

contact:
	contactID [int]
	contactName [varchar]
	contactEmail [varchar]
	contactPhoneNo [varchar]

message:
	messageID [int]
	messageSubject [varchar]
	messageContent [text]
	messageCreatedDate [datetime]

menu:
	menuID [int]
	siteID [int]
	menuType [int]		## 1 = top
	componentNo [int]
	menuName [varchar]
	menuRefID [int]		## if componentID = 1 (page), refer to page id.
	menuRoute [varchar] ## if componentNo = 99, custom. else, empty.
	menuNo [int]		## to sort by listing.

component:	## static record, 6 currently.
	componentNo [int]				## 1 = page, 2 = main (/), 3 =  activity, 4 = members, 5 = contact us, 99 = custom.
	componentName [varchar]
	componentRoute [varchar]		## controller/action or route.
	componentStatus [int]			## 0 = inactive (wont show menu), 1 = activated.

page: 		## by default, will create about me page.
	pageID [int]
	siteID [int]
	pageApprovedStatus [int]	## 0 = unapproved, 1 = approve, 2 = unapproved.
	pageName [varchar]
	pageSlug [varchar]			## page slug
	pageText [text]
	pageType [int]			## 1 = default, 2 = manual, 3 = general page
	pageDefaultType [int]	## if pageType is 0, this column is 0. 1 = about-us, 2 = about-pengurus, 3 = about-kampung.
	pageCreatedUser [int]
	pageCreatedDate [datetime]
	pageUpdatedUser [int]
	pageUpdatedDate [datetime]

page_photo:
	pagePhotoID [int]
	pageID [int]
	photoID [int]

page_reference:
	pageReferenceID [int]
	pageParentID [int]
	pageID [int]

page_default:
	pageDefaultID [int]
	pageDefaultType [varchar]	## 1 = about-us, 2 = about-pengurus, 3 = about-kampung.
	pageDefaultName [varchar]
	pageDefaultSlug [varchar]

## site editor can see article with articleStatus = 1 (saved).
article:
	articleID [int]
	siteID [int]
	articleStatus [int]		## 0 = unapproved, 1 = approved, 2 = disapproved, 3 = draft
	articleSlug [varchar]
	articleOriginalSlug [varchar]
	articleName [varchar]
	articleText [text]
	articlePublishedDate [datetime]		## will only published after this date.
	articleCreatedUser [int]
	articleCreatedDate [datetime]
	articleUpdatedUser [int]
	articleUpdatedDate [datetime]

article_photo:
	photoArticleID [int]
	photoID [int]
	articleID [int]
	articlePhotoCreatedDate [datetime]
	articlePhotoCreatedUser [int]

article_tag:
	articleTagID [int]
	articleID [int]	## article ID
	articleTagName [varchar]

announcement:
	announcementID [int]
	siteID [int]					## 0 = all sites, !0 = specific site
	announcementStatus [int]		## 0 = not appeared, 1 = appeared, 2 = unapproved.
	announcementText [text]
	announcementLink [text]
	announcementCreatedUser [int]
	announcementCreatedDate [datetime]
	announcementUpdatedUser [int]
	announcementUpdatedDate [datetime]
	announcementExpiredDate [datetime]

site_manager:
	siteManagerID [int]
	userID [int]
	siteID [int]
	siteManagerStatus [int]		## 1 = active, 0 = deactived.
	siteManagerCreatedDate [datetime]
	siteManagerCreatedUser [int]
	siteManagerUpdatedDate [datetime]
	siteManagerUpdatedUser [int]

cluster:
	clusterID [int]
	clusterName [varchar]
	clusterCreatedDate [datetime]
	clusterCreatedUser [int]

cluster_site: # many site to one cluster.
	clusterSiteID [int]
	siteID [int]
	clusterID [int]

cluster_lead:
	clusterLeadID [int]
	clusterID [int]
	userID [int]
	clusterLeadStatus [int] ## 1 = active, 0 = inactive.
	clusterLeadCreatedDate [datetime]
	clusterLeadCreatedUser [int]

album:
	albumID [int]
	albumType [int]			## 1 = user-album, 2 = site-album
	albumName [varchar]
	albumCoverImageName [varchar] ## relative url for photo.
	albumDescription [text]
	albumCreatedDate [datetime]
	albumCreatedUser [int]

site_album:
	siteAlbumID [int]
	albumID [int]
	siteID [int]
	siteAlbumType [int] ## 1 = activity-album.

user_album:
	userAlbumID [int]
	albumID [int]
	userID [int]

photo:
	photoID [int]
	albumID [int]			## 0 is no album, else album based.
	photoType [int]			## 1 = user-photo, 2 = site-photo, 0 = unrelated.
	photoName [varchar]			## photo full saved name, (path included)
	photoOriginalName [varchar]	## original photo name.
	photoDescription [text]
	photoCreatedDate [datetime]
	photoCreatedUser [int]

site_request: ## table to store update request or anything regarding site, have, status.
	siteRequestID [int]
	siteRequestType [varchar]					## 1 = new pages, 2 = page edit, 3 = site edit, 4 = new site announcement
	siteID [int]
	siteRequestRefID [int]					## reference-id
	siteRequestData [text]
	siteRequestStatus [int]					## 0 = unapproved, 1 = approved, 2 = disapproved
	siteRequestApprovalRead [int]
	siteRequestCreatedDate [datetime]
	siteRequestCreatedUser [int]
	siteRequestUpdatedDate [datetime]
	siteRequestUpdatedUser [int]

token:
	tokenID [int]
	tokenType [int]		## 1 = reset password.
	tokenName [varchar]
	tokenStatus [int]	## status 1 = active, 2 = expired.
	tokenCreatedDate [datetime]
	tokenUpdatedDate [datetime]

token_resetpass:
	tokenResetpassID [int]
	tokenID [int]
	userID [int]
	tokenResetpassStatus [int] ## 0 = in-active, 1 = active (after user has accessed the link), 2 = reset success. 